name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
