name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.0"
      - name: Run tests
        run: swift test -v
