#!/usr/bin/env bash


GIT_ROOT=$(git rev-parse --show-toplevel)

SWIFT_FORMAT_OUTPUT=$($GIT_ROOT/Scripts/lint-swift-code)
RETURNED_ERROR=$?

if [ $RETURNED_ERROR -ne 0 ]; then
  echo "Error: Swift code is not formatted correctly. Please run 'swift-format format' to fix most errors."
  echo "$SWIFT_FORMAT_OUTPUT"
fi

exit $RETURNED_ERROR